### PR TITLE
Resolve #11

### LINKED ISSUE #11: Add style guide for Angular 1.x
Nothing fancy, use John Papa's style guide as reference.

### PR DESCRIPTION
**Pull request by MohammedSiddiqui**
Copy Pasted John Papa's README.md with some minor changes:
- Changed references in sentences where "I" or "my" were being used.
- Removed some contents such as "File Templates and Snippets" and "Yeoman generator".
- Added assets folder in repository and referenced them inside the new readme.

### CODE REVIEW

**Comment by MohammedSiddiqui** [comment]
I wasn't sure whether or not to redo the sections about Task Automation by removing Grunt and Gulp references to use Webpack instead. And same goes for linting, to replace JSHint with ESLint

**Comment by mohuk** [comment]
@MohammedSiddiqui excellent stuff and you are correct on the webpack and ESLint approach. JSHint, Grunt/Gulp should be replaced.

**Comment by mohuk** [comment]
@MohammedSiddiqui is it still up to date?

**Comment by MohammedSiddiqui** [comment]
I think it would be wiser if I close this pull request and create a new one, forking Todd Motto's style-guide instead, https://github.com/toddmotto/angular-styleguide
It relates far better to how things work with Angular 1.5+ and ES6.
What do you think ?

**Comment by MohammedSiddiqui** [comment]
@mohuk

**Comment by mohuk** [comment]
@MohammedSiddiqui Agreed, pull in Todd Moto's guide

**Pull request closed without merging**
