### PR TITLE
Added OCLint installation and integration guidelines.

### PR DESCRIPTION
**Pull request by waheeda**

### CODE REVIEW

**Comment by mohuk** [comment]
Thanks for the awesome work. 

Unfortunately for the content to show up correctly, you'd have to convert it to markdown. Take a look at the existing guides to take example. Help can be found at the [markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

**Comment by waheeda** [comment]
please check now.

**Comment by mohuk** [comment]
I can't find the `lint` file in this PR. Is it something you missed out in the commits ?

**Comment by ubaid-me** [comment]
@waheeda-ghani-10p using OCLint will we have a separate ```lint``` file Or it will utilize some default config? Can you please respond so that @mohuk can proceed with this PR

**Comment by waheeda-ghani-10p** [comment]
@mohuk @ubaidurrehman-10p  We are using default rules for now.

**Pull request merged**
