### PR TITLE
Close #6: ES6 Style Guide

### LINKED ISSUE #6: Javascript: Add guide for es6

### PR DESCRIPTION
**Pull request by umayr**
This PR adds a forked version of Airbnb's Javascript Style Guide with a few modifications.

### CODE REVIEW

**Comment by mohuk** [comment]
Should we make a JS Style guide landing page and then put the relvent links inside that landing page and each guide can then we a separate markdown file?

**Comment by umayr** [comment]
We can move once we add more guides in javascript folder.

**Comment by mohuk** [comment]
We can also get rid of `jscs` and `jshint`

**Comment by umayr** [comment]
> We can also get rid of jscs and jshint

Done.

**Pull request merged**
